services:
  - type: web
    name: plant-disease-api
    env: python
    buildCommand: |
      pyenv install -s 3.10.13
      pyenv global 3.10.13
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn api:app
